name: breezy_look
description: "Breezy days, stylish ways."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.17
  shared_preferences: ^2.5.2
  http: ^1.3.0
  firebase_core: ^3.13.0
  provider: ^6.1.4
  firebase_auth: ^5.5.2
  geolocator: ^14.0.0
  intl: ^0.20.2
  geocoding: ^3.0.0
  flutter_dotenv: ^5.2.1
  google_sign_in: ^6.3.0
  image_picker: ^1.1.2
  image_cropper: ^9.1.0
  cloud_firestore: ^5.6.8
  supabase_flutter: ^2.9.0
  flutter_native_splash: ^2.4.6
  # firebase_storage: ^12.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon/icon_breezylook.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons/app_icon/
    - assets/fashion_items/
    - assets/icons/
    - assets/fonts/geist_ttf/
    - assets/user/

  fonts:
    - family: Geist
      fonts:
        - asset: assets/fonts/geist_ttf/Geist-Thin.ttf
        - asset: assets/fonts/geist_ttf/Geist-SemiBold.ttf
        - asset: assets/fonts/geist_ttf/Geist-Regular.ttf
        - asset: assets/fonts/geist_ttf/Geist-Medium.ttf
        - asset: assets/fonts/geist_ttf/Geist-Light.ttf
        - asset: assets/fonts/geist_ttf/Geist-ExtraLight.ttf
        - asset: assets/fonts/geist_ttf/Geist-ExtraBold.ttf
        - asset: assets/fonts/geist_ttf/Geist-Bold.ttf
        - asset: assets/fonts/geist_ttf/Geist-Black.ttf
